import { Event, EventType } from "./event";

export const events: Event[] = [
    {
        id: '1',
        title: 'Hackathon1',
        subtitle: 'Hackathon subtitle',
        description: 'Hackathon description',
        wallet: '0x1234567890',
        image: '/hackers.jpeg',
        type: EventType.HACKER_HOUSE,
        organisers: ['Paul'],
        sponsors: ['Starknet, Optimism'],
        location: 'London',
        requested_funding: 1000,
        received_funding: 0,
        start_date: '2021-06-15',
        end_date: '2021-06-16'
    },
    {
        id: '2',
        title: 'Hackathon2',
        subtitle: 'Hackathon subtitle',
        description: 'Hackathon description',
        wallet: '0x1234567890',
        image: '/hackers.jpeg',
        type: EventType.HACKER_HOUSE,
        organisers: ['Paul'],
        sponsors: ['Starknet, Optimism'],
        location: 'London',
        requested_funding: 1000,
        received_funding: 0,
        start_date: '2021-06-15',
        end_date: '2021-06-16'
    },
    {
        id: '3',
        title: 'Hackathon3',
        subtitle: 'Hackathon subtitle',
        description: 'Hackathon description',
        wallet: '0x1234567890',
        image: '/hackers.jpeg',
        type: EventType.HACKER_HOUSE,
        organisers: ['Paul'],
        sponsors: ['Starknet, Optimism'],
        location: 'London',
        requested_funding: 1000,
        received_funding: 0,
        start_date: '2021-06-15',
        end_date: '2021-06-16'
    },
    {
        id: '4',
        title: 'Hackathon4',
        subtitle: 'Hackathon subtitle',
        description: 'Hackathon description',
        wallet: '0x1234567890',
        image: '/hackers.jpeg',
        type: EventType.HACKER_HOUSE,
        organisers: ['Paul'],
        sponsors: ['Starknet, Optimism'],
        location: 'London',
        requested_funding: 1000,
        received_funding: 0,
        start_date: '2021-06-15',
        end_date: '2021-06-16'
    },
    {
        id: '5',
        title: 'Hackathon5',
        subtitle: 'Hackathon subtitle',
        description: 'Hackathon description',
        wallet: '0x1234567890',
        image: '/hackers.jpeg',
        type: EventType.HACKER_HOUSE,
        organisers: ['Paul'],
        sponsors: ['Starknet, Optimism'],
        location: 'London',
        requested_funding: 1000,
        received_funding: 0,
        start_date: '2021-06-15',
        end_date: '2021-06-16'
    },
    {
        id: '6',
        title: 'Hackathon6',
        subtitle: 'Hackathon subtitle',
        description: 'Hackathon description',
        wallet: '0x1234567890',
        image: '/hackers.jpeg',
        type: EventType.HACKER_HOUSE,
        organisers: ['Paul'],
        sponsors: ['Starknet, Optimism'],
        location: 'London',
        requested_funding: 1000,
        received_funding: 0,
        start_date: '2021-06-15',
        end_date: '2021-06-16'
    },
    {
        id: '7',
        title: 'Hackathon7',
        subtitle: 'Hackathon subtitle',
        description: 'Hackathon description',
        wallet: '0x1234567890',
        image: '/hackers.jpeg',
        type: EventType.HACKER_HOUSE,
        organisers: ['Paul'],
        sponsors: ['Starknet, Optimism'],
        location: 'London',
        requested_funding: 1000,
        received_funding: 0,
        start_date: '2021-06-15',
        end_date: '2021-06-16'
    },
    {
        id: '8',
        title: 'Hackathon8',
        subtitle: 'Hackathon subtitle',
        description: 'Hackathon description',
        wallet: '0x1234567890',
        image: '/hackers.jpeg',
        type: EventType.HACKER_HOUSE,
        organisers: ['Paul'],
        sponsors: ['Starknet, Optimism'],
        location: 'London',
        requested_funding: 1000,
        received_funding: 0,
        start_date: '2021-06-15',
        end_date: '2021-06-16'
    },
    {
        id: '9',
        title: 'Hackathon9',
        subtitle: 'Hackathon subtitle',
        description: 'Hackathon description',
        wallet: '0x1234567890',
        image: '/hackers.jpeg',
        type: EventType.HACKER_HOUSE,
        organisers: ['Paul'],
        sponsors: ['Starknet, Optimism'],
        location: 'London',
        requested_funding: 1000,
        received_funding: 0,
        start_date: '2021-06-15',
        end_date: '2021-06-16'
    },
    {
        id: '10',
        title: 'Hackathon10',
        subtitle: 'Hackathon subtitle',
        description: 'Hackathon description',
        wallet: '0x1234567890',
        image: '/hackers.jpeg',
        type: EventType.HACKER_HOUSE,
        organisers: ['Paul'],
        sponsors: ['Starknet, Optimism'],
        location: 'London',
        requested_funding: 1000,
        received_funding: 0,
        start_date: '2021-06-15',
        end_date: '2021-06-16'
    },
    {
        id: '11',
        title: 'Hackathon11',
        subtitle: 'Hackathon subtitle',
        description: 'Hackathon description',
        wallet: '0x1234567890',
        image: '/hackers.jpeg',
        type: EventType.HACKER_HOUSE,
        organisers: ['Paul'],
        sponsors: ['Starknet, Optimism'],
        location: 'London',
        requested_funding: 1000,
        received_funding: 0,
        start_date: '2021-06-15',
        end_date: '2021-06-16'
    },
    {
        id: '12',
        title: 'Hackathon12',
        subtitle: 'Hackathon subtitle',
        description: 'Hackathon description',
        wallet: '0x1234567890',
        image: '/hackers.jpeg',
        type: EventType.HACKER_HOUSE,
        organisers: ['Paul'],
        sponsors: ['Starknet, Optimism'],
        location: 'London',
        requested_funding: 1000,
        received_funding: 0,
        start_date: '2021-06-15',
        end_date: '2021-06-16'
    },
]

export const users: User[] = [
    {
        username: 'Paul',
        email: 'Paul@gmail.com',
    },
    {
        username: 'Samuel',
        email: 'Samuel@gmail.com',
    },
]

export const featuredEvents: Event[] = [
    {
        id: '1',
        title: 'Hackathon1',
        subtitle: 'Hackathon subtitle',
        description: 'Hackathon description',
        wallet: '0x1234567890',
        image: '/hackers.jpeg',
        type: EventType.HACKER_HOUSE,
        organisers: ['Paul'],
        sponsors: ['Starknet, Optimism'],
        location: 'London',
        requested_funding: 1000,
        received_funding: 0,
        start_date: '2021-06-15',
        end_date: '2021-06-16'
    },
    {
        id: '2',
        title: 'Hackathon2',
        subtitle: 'Hackathon subtitle',
        description: 'Hackathon description',
        wallet: '0x1234567890',
        image: '/hackers.jpeg',
        type: EventType.HACKER_HOUSE,
        organisers: ['Paul'],
        sponsors: ['Starknet, Optimism'],
        location: 'London',
        requested_funding: 1000,
        received_funding: 0,
        start_date: '2021-06-15',
        end_date: '2021-06-16'
    },
    {
        id: '3',
        title: 'Hackathon3',
        subtitle: 'Hackathon subtitle',
        description: 'Hackathon description',
        wallet: '0x1234567890',
        image: '/hackers.jpeg',
        type: EventType.HACKER_HOUSE,
        organisers: ['Paul'],
        sponsors: ['Starknet, Optimism'],
        location: 'London',
        requested_funding: 1000,
        received_funding: 0,
        start_date: '2021-06-15',
        end_date: '2021-06-16'
    },
    {
        id: '4',
        title: 'Hackathon4',
        subtitle: 'Hackathon subtitle',
        description: 'Hackathon description',
        wallet: '0x1234567890',
        image: '/hackers.jpeg',
        type: EventType.HACKER_HOUSE,
        organisers: ['Paul'],
        sponsors: ['Starknet, Optimism'],
        location: 'London',
        requested_funding: 1000,
        received_funding: 0,
        start_date: '2021-06-15',
        end_date: '2021-06-16'
    }, 
]